"""Post-processing: fix all French accents/typos in generated PPTX"""
from pptx import Presentation
import re, sys

REPLACEMENTS = {
    "Comprehension": "Compr\u00e9hension",
    "comprehension": "compr\u00e9hension",
    "Strategiques": "Strat\u00e9giques",
    "strategiques": "strat\u00e9giques",
    "Ajoutees": "Ajout\u00e9es",
    "ajoutees": "ajout\u00e9es",
    "Ajoutee": "Ajout\u00e9e",
    "ajoutee": "ajout\u00e9e",
    "Academie": "Acad\u00e9mie",
    "academie": "acad\u00e9mie",
    "Methodes": "M\u00e9thodes",
    "methodes": "m\u00e9thodes",
    "Pedagogiques": "P\u00e9dagogiques",
    "pedagogiques": "p\u00e9dagogiques",
    "pedagogique": "p\u00e9dagogique",
    "Evaluation": "\u00c9valuation",
    "evaluation": "\u00e9valuation",
    "Fonctionnalites": "Fonctionnalit\u00e9s",
    "fonctionnalites": "fonctionnalit\u00e9s",
    "Avancees": "Avanc\u00e9es",
    "avancees": "avanc\u00e9es",
    "Securite": "S\u00e9curit\u00e9",
    "securite": "s\u00e9curit\u00e9",
    "securise": "s\u00e9curis\u00e9",
    "securises": "s\u00e9curis\u00e9s",
    "securisee": "s\u00e9curis\u00e9e",
    "Identite": "Identit\u00e9",
    "identite": "identit\u00e9",
    "Strategie": "Strat\u00e9gie",
    "strategie": "strat\u00e9gie",
    "Referencement": "R\u00e9f\u00e9rencement",
    "referencement": "r\u00e9f\u00e9rencement",
    "Reseaux": "R\u00e9seaux",
    "reseaux": "r\u00e9seaux",
    "Evolutions": "\u00c9volutions",
    "evolutions": "\u00e9volutions",
    "Integre": "Int\u00e9gr\u00e9",
    "integre": "int\u00e9gr\u00e9",
    "Integree": "Int\u00e9gr\u00e9e",
    "integree": "int\u00e9gr\u00e9e",
    "Integrees": "Int\u00e9gr\u00e9es",
    "integrees": "int\u00e9gr\u00e9es",
    "Integration": "Int\u00e9gration",
    "integration": "int\u00e9gration",
    "Integrations": "Int\u00e9grations",
    "integrations": "int\u00e9grations",
    "Experience": "Exp\u00e9rience",
    "experience": "exp\u00e9rience",
    "Personnalise": "Personnalis\u00e9",
    "personnalise": "personnalis\u00e9",
    "personnalisee": "personnalis\u00e9e",
    "personnalisees": "personnalis\u00e9es",
    "personnalises": "personnalis\u00e9s",
    "Personnalises": "Personnalis\u00e9s",
    "enregistrees": "enregistr\u00e9es",
    "enregistres": "enregistr\u00e9s",
    "pre-enregistrees": "pr\u00e9-enregistr\u00e9es",
    "dediee": "d\u00e9di\u00e9e",
    "dedies": "d\u00e9di\u00e9s",
    "dedie": "d\u00e9di\u00e9",
    "detaillee": "d\u00e9taill\u00e9e",
    "detaillees": "d\u00e9taill\u00e9es",
    "detailles": "d\u00e9taill\u00e9s",
    "detaille": "d\u00e9taill\u00e9",
    "Detailles": "D\u00e9taill\u00e9s",
    "certifiantes": "certifiantes",
    "structurees": "structur\u00e9es",
    "Deploiement": "D\u00e9ploiement",
    "deploiement": "d\u00e9ploiement",
    "Developpement": "D\u00e9veloppement",
    "developpement": "d\u00e9veloppement",
    "Presentation": "Pr\u00e9sentation",
    "presentation": "pr\u00e9sentation",
    "Evenements": "\u00c9v\u00e9nements",
    "evenements": "\u00e9v\u00e9nements",
    "Prepare": "Pr\u00e9par\u00e9",
    "prepare": "pr\u00e9par\u00e9",
    "reference": "r\u00e9f\u00e9rence",
    "Reference": "R\u00e9f\u00e9rence",
    "Generation": "G\u00e9n\u00e9ration",
    "generation": "g\u00e9n\u00e9ration",
    "Generale": "G\u00e9n\u00e9rale",
    "generale": "g\u00e9n\u00e9rale",
    "complementaires": "compl\u00e9mentaires",
    "completement": "compl\u00e8tement",
    "immediat": "imm\u00e9diat",
    "interactifs": "interactifs",
    "modele": "mod\u00e8le",
    "Modele": "Mod\u00e8le",
    "probleme": "probl\u00e8me",
    "systeme": "syst\u00e8me",
    "Systeme": "Syst\u00e8me",
    "particulierement": "particuli\u00e8rement",
    "completees": "compl\u00e9t\u00e9es",
    "Specialise": "Sp\u00e9cialis\u00e9",
    "specialise": "sp\u00e9cialis\u00e9",
    "debutant": "d\u00e9butant",
    "recus": "re\u00e7us",
    "Recus": "Re\u00e7us",
    "factures": "factures",
    "automatises": "automatis\u00e9s",
    "Automatises": "Automatis\u00e9s",
    "automatisee": "automatis\u00e9e",
    "automatisees": "automatis\u00e9es",
    "gamifies": "gamifi\u00e9s",
    "Gamifies": "Gamifi\u00e9s",
    "gamifie": "gamifi\u00e9",
    "gamifiees": "gamifi\u00e9es",
    "cibles": "cibl\u00e9s",
    "ciblees": "cibl\u00e9es",
    "ciblee": "cibl\u00e9e",
    "cible": "cibl\u00e9",
    "avancee": "avanc\u00e9e",
    "optimisee": "optimis\u00e9e",
    "optimisees": "optimis\u00e9es",
    "optimises": "optimis\u00e9s",
    "Optimisees": "Optimis\u00e9es",
    "renforce": "renforc\u00e9",
    "renforcee": "renforc\u00e9e",
    "Renforcee": "Renforc\u00e9e",
    "inspirante": "inspirante",
    "donnees": "donn\u00e9es",
    "Donnees": "Donn\u00e9es",
    "Activite": "Activit\u00e9",
    "activite": "activit\u00e9",
    "communaute": "communaut\u00e9",
    "Communaute": "Communaut\u00e9",
    "Communautaire": "Communautaire",
    "communautaire": "communautaire",
    "Fidele": "Fid\u00e8le",
    "fidele": "fid\u00e8le",
    "fidelite": "fid\u00e9lit\u00e9",
    "Fidelite": "Fid\u00e9lit\u00e9",
    "Fidelisation": "Fid\u00e9lisation",
    "fidelisation": "fid\u00e9lisation",
    "interieure": "int\u00e9rieure",
    "recompenses": "r\u00e9compenses",
    "Recompenses": "R\u00e9compenses",
    "desireux": "d\u00e9sireux",
    "equipe": "\u00e9quipe",
    "Equipe": "\u00c9quipe",
    "ecrans": "\u00e9crans",
    "Ecrans": "\u00c9crans",
    "echanges": "\u00e9changes",
    "Echanges": "\u00c9changes",
    "Etoiles": "\u00c9toiles",
    "etoiles": "\u00e9toiles",
    "telephone": "t\u00e9l\u00e9phone",
    "Telephone": "T\u00e9l\u00e9phone",
    "immediat": "imm\u00e9diat",
    "renouvellement": "renouvellement",
    "Exercices": "Exercices",
    "regulier": "r\u00e9gulier",
    "reguliers": "r\u00e9guliers",
    "particulier": "particulier",
    "trimestriel": "trimestriel",
    "performante": "performante",
    "Recommandations": "Recommandations",
    "recommandations": "recommandations",
    "Spirituel": "Spirituel",
    "previsions": "pr\u00e9visions",
    "Previsions": "Pr\u00e9visions",
    "genereux": "g\u00e9n\u00e9reux",
    "Genereux": "G\u00e9n\u00e9reux",
    "professionnel": "professionnel",
    "Etape": "\u00c9tape",
    "etape": "\u00e9tape",
    "decouverte": "d\u00e9couverte",
    "Decouverte": "D\u00e9couverte",
    "seminaire": "s\u00e9minaire",
    "Seminaire": "S\u00e9minaire",
    "academie": "acad\u00e9mie",
    "Academie": "Acad\u00e9mie",
    "Calendrier": "Calendrier",
    "retention": "r\u00e9tention",
    "Retention": "R\u00e9tention",
    "Recurrence": "R\u00e9currence",
    "recurrence": "r\u00e9currence",
    "entonnoir": "entonnoir",
    "relances": "relances",
    "Relances": "Relances",
    "abandonne": "abandonn\u00e9",
    "inactivite": "inactivit\u00e9",
    "interet": "int\u00e9r\u00eat",
    "completees": "compl\u00e9t\u00e9es",
    "Completees": "Compl\u00e9t\u00e9es",
    "personnalise": "personnalis\u00e9",
    "Partageables": "Partageables",
    "partageables": "partageables",
    "indexes": "index\u00e9s",
    "Indexes": "Index\u00e9s",
    "duree": "dur\u00e9e",
    "Duree": "Dur\u00e9e",
    "prerequis": "pr\u00e9requis",
    "Prerequis": "Pr\u00e9requis",
    "phares": "phares",
    "d'inactivite": "d'inactivit\u00e9",
    "Viralite": "Viralit\u00e9",
    "viralite": "viralit\u00e9",
    "intuitif": "intuitif",
    "Actualites": "Actualit\u00e9s",
    "actualites": "actualit\u00e9s",
    "creer": "cr\u00e9er",
    "Creer": "Cr\u00e9er",
    "disponibilite": "disponibilit\u00e9",
    "Disponibilite": "Disponibilit\u00e9",
}

def fix_text(text):
    if not text:
        return text
    for wrong, right in sorted(REPLACEMENTS.items(), key=lambda x: -len(x[0])):
        if wrong in text and right != wrong:
            text = text.replace(wrong, right)
    return text

def process(input_path, output_path):
    prs = Presentation(input_path)
    count = 0
    for slide in prs.slides:
        for shape in slide.shapes:
            if shape.has_text_frame:
                for para in shape.text_frame.paragraphs:
                    for run in para.runs:
                        old = run.text
                        new = fix_text(old)
                        if new != old:
                            run.text = new
                            count += 1
    prs.save(output_path)
    print(f"Fixed {count} text runs. Saved: {output_path}")

if __name__ == "__main__":
    inp = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else inp
    process(inp, out)
